### ISSUE TITLE
Slack logger intermittent failure

### ISSUE THREAD

**Issue by placer14** [nation-of-makers/nom-slack-logger#1]
Slack logger intermittantly stops. Log output during failure follows.

```
18:31:56 bot.1  |  ~ (0.000757) COMMIT
18:31:56 bot.1  |  ~ (0.005495) INSERT INTO "users" ("id") VALUES ('U2YHD6KMM')
18:31:56 bot.1  |  ~ ERROR:  duplicate key value violates unique constraint "users_pkey"
18:31:56 bot.1  | DETAIL:  Key (id)=(U2YHD6KMM) already exists.
18:31:56 bot.1  |  (code: 83906754, sql state: 23505, query: INSERT INTO "users" ("id") VALUES ('U2YHD6KMM'), uri: postgres:postgres@db/nom_db?scheme=postgres&user=postgres&password=auniquepasswordnoonewillguess123&host=db&port=&path=/nom_db&query=&fragment=&adapter=postgres)
18:31:56 bot.1  | DataObjects::IntegrityError: ERROR:  duplicate key value violates unique constraint "users_pkey"
18:31:56 bot.1  | DETAIL:  Key (id)=(U2YHD6KMM) already exists.
18:31:56 bot.1  |  ~ (0.000353) SELECT "id", "name", "real_name", "image" FROM "users" WHERE "id" = 'U2YHD6KMM' ORDER BY "id" LIMIT 1
18:31:56 bot.1  |  ~ ERROR:  current transaction is aborted, commands ignored until end of transaction block
18:31:56 bot.1  |  (code: 33685826, sql state: 25P02, query: SELECT "id", "name", "real_name", "image" FROM "users" WHERE "id" = 'U2YHD6KMM' ORDER BY "id" LIMIT 1, uri: postgres:postgres@db/nom_db?scheme=postgres&user=postgres&password=auniquepasswordnoonewillguess123&host=db&port=&path=/nom_db&query=&fragment=&adapter=postgres)
18:31:56 bot.1  | DataObjects::TransactionError: ERROR:  current transaction is aborted, commands ignored until end of transaction block
18:31:56 bot.1  |  ~ (0.000307) SELECT "id", "name", "real_name", "image" FROM "users" WHERE "id" = 'U2YHD6KMM' ORDER BY "id" LIMIT 1
18:31:56 bot.1  |  ~ ERROR:  current transaction is aborted, commands ignored until end of transaction block
18:31:56 bot.1  |  (code: 33685826, sql state: 25P02, query: SELECT "id", "name", "real_name", "image" FROM "users" WHERE "id" = 'U2YHD6KMM' ORDER BY "id" LIMIT 1, uri: postgres:postgres@db/nom_db?scheme=postgres&user=postgres&password=auniquepasswordnoonewillguess123&host=db&port=&path=/nom_db&query=&fragment=&adapter=postgres)
18:31:56 bot.1  | DataObjects::TransactionError: ERROR:  current transaction is aborted, commands ignored until end of transaction block
18:31:56 bot.1  |  ~ (0.000287) INSERT INTO "messages" ("channel_id", "text", "timestamp") VALUES ('C25J378F4', '<@U2YHD6KMM|ptone> has joined the channel', '2016-11-03T18:31:56+00:00') RETURNING "id"
18:31:56 bot.1  |  ~ ERROR:  current transaction is aborted, commands ignored until end of transaction block
18:31:56 bot.1  |  (code: 33685826, sql state: 25P02, query: INSERT INTO "messages" ("channel_id", "text", "timestamp") VALUES ('C25J378F4', '<@U2YHD6KMM|ptone> has joined the channel', '2016-11-03T18:31:56+00:00') RETURNING "id", uri: postgres:postgres@db/nom_db?scheme=postgres&user=postgres&password=auniquepasswordnoonewillguess123&host=db&port=&path=/nom_db&query=&fragment=&adapter=postgres)
18:31:56 bot.1  |  ~ default: rollback
18:31:56 bot.1  |  ~ (0.000109) ROLLBACK
18:31:56 bot.1  | D, [2016-11-03T18:31:56.681192 #13] DEBUG -- : RTM connection closed: 1006,
18:31:56 bot.1  | /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:114:in `execute_non_query': ERROR:  current transaction is aborted, commands ignored until end of transaction block (DataObjects::TransactionError)
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:114:in `block (2 levels) in create'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:113:in `block in create'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:85:in `each'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:85:in `create'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/repository.rb:146:in `create'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/transient.rb:74:in `create_resource'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/transient.rb:25:in `commit'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:963:in `_persist'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:977:in `block in create_with_hooks'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:974:in `catch'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:974:in `create_with_hooks'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:1028:in `save_self'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-validations-1.2.0/lib/dm-validations.rb:54:in `save_self'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:1013:in `block in _save'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:1229:in `run_once'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:1012:in `_save'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-core-1.2.1/lib/dm-core/resource.rb:412:in `save'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-validations-1.2.0/lib/dm-validations.rb:40:in `block in save'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-validations-1.2.0/lib/dm-validations/context.rb:16:in `in_context'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-validations-1.2.0/lib/dm-validations.rb:40:in `save'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-validations-1.2.0/lib/dm-validations.rb:130:in `create'
18:31:56 bot.1  | 	from /usr/src/app/tech404logs/lib/tech404logs/message.rb:17:in `block in store'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:373:in `block in transaction'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:131:in `block in commit'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:195:in `within'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:131:in `commit'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/dm-transactions-1.2.0/lib/dm-transactions.rb:373:in `transaction'
18:31:56 bot.1  | 	from /usr/src/app/tech404logs/lib/tech404logs/message.rb:16:in `store'
18:31:56 bot.1  | 	from /usr/src/app/tech404logs/lib/tech404logs/message_handler.rb:21:in `handle'
18:31:56 bot.1  | 	from /usr/src/app/tech404logs/lib/tech404logs/message_handler.rb:4:in `handle'
18:31:56 bot.1  | 	from /usr/src/app/tech404logs/lib/tech404logs/event_handler.rb:17:in `handle'
18:31:56 bot.1  | 	from /usr/src/app/tech404logs/lib/tech404logs/event_handler.rb:4:in `handle'
18:31:56 bot.1  | 	from /usr/src/app/tech404logs/lib/tech404logs/connection.rb:41:in `block in on_message'
18:31:56 bot.1  | 	from /usr/local/bundle/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
18:31:56 bot.1  | exited with code 1
18:31:56 system | sending SIGTERM to all processes
18:31:56 web.1  | [14] - Gracefully shutting down workers...
18:31:56 web.1  | [14] === puma shutdown: 2016-11-03 18:31:56 +0000 ===
18:31:56 web.1  | [14] - Goodbye!
18:31:56 web.1  | exited with code 0
fatal: Not a git repository (or any parent up to mount point /usr/src/app/tech404logs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
 ~ (0.002473) SET backslash_quote = off
 ~ (0.000768) SET standard_conforming_strings = on
 ~ (0.000080) SET client_min_messages = warning
 ~ (0.000252) SET datestyle = ISO
 ~ (0.000069) SET client_min_messages = warning
 ~ (0.000075) SET client_min_messages = warning
 ~ (0.001990) SELECT current_schema()
 ~ (0.008323) SELECT COUNT(*) FROM "information_schema"."tables" WHERE "table_type" = 'BASE TABLE' AND "table_schema" = 'public' AND "table_name" = 'channels'
 ~ (0.000187) RESET client_min_messages
 ~ (0.000212) SET backslash_quote = off
 ~ (0.000103) SET standard_conforming_strings = on
 ~ (0.000093) SET client_min_messages = warning
 ~ (0.000105) SET datestyle = ISO
 ~ (0.010201) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'channels' AND "column_name" = 'id'
 ~ (0.002188) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'channels' AND "column_name" = 'name'
 ~ (0.002229) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'channels' AND "column_name" = 'creator_id'
 ~ (0.003109) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'channels' AND "column_name" = 'member'
 ~ (0.000176) RESET client_min_messages
 ~ (0.000134) SET client_min_messages = warning
 ~ (0.000111) SET client_min_messages = warning
 ~ (0.001823) SELECT COUNT(*) FROM "information_schema"."tables" WHERE "table_type" = 'BASE TABLE' AND "table_schema" = 'public' AND "table_name" = 'messages'
 ~ (0.000123) RESET client_min_messages
 ~ (0.003148) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'messages' AND "column_name" = 'id'
 ~ (0.001914) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'messages' AND "column_name" = 'channel_id'
 ~ (0.001724) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'messages' AND "column_name" = 'user_id'
 ~ (0.001631) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'messages' AND "column_name" = 'text'
 ~ (0.001665) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'messages' AND "column_name" = 'timestamp'
 ~ (0.000119) RESET client_min_messages
 ~ (0.000086) SET client_min_messages = warning
 ~ (0.000074) SET client_min_messages = warning
 ~ (0.000985) SELECT COUNT(*) FROM "information_schema"."tables" WHERE "table_type" = 'BASE TABLE' AND "table_schema" = 'public' AND "table_name" = 'users'
 ~ (0.000076) RESET client_min_messages
 ~ (0.001765) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'users' AND "column_name" = 'id'
 ~ (0.001613) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'users' AND "column_name" = 'name'
 ~ (0.001658) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'users' AND "column_name" = 'real_name'
 ~ (0.001603) SELECT COUNT(*) FROM "information_schema"."columns" WHERE "table_schema" = 'public' AND "table_name" = 'users' AND "column_name" = 'image'
 ~ (0.000113) RESET client_min_messages
fatal: Not a git repository (or any parent up to mount point /usr/src/app/tech404logs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
04:02:02 bot.1  | started with pid 13
04:02:02 web.1  | started with pid 14
04:02:02 web.1  | fatal: Not a git repository (or any parent up to mount point /usr/src/app/tech404logs)
04:02:02 web.1  | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
04:02:02 bot.1  | fatal: Not a git repository (or any parent up to mount point /usr/src/app/tech404logs)
04:02:02 bot.1  | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
04:02:04 web.1  | [14] Puma starting in cluster mode...
04:02:04 web.1  | [14] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
04:02:04 web.1  | [14] * Min threads: 5, max threads: 5
04:02:04 web.1  | [14] * Environment: development
04:02:04 web.1  | [14] * Process workers: 2
04:02:04 web.1  | [14] * Preloading application
04:02:04 web.1  | [14] * Listening on tcp://0.0.0.0:8100
04:02:04 web.1  | [14] Use Ctrl-C to stop
04:02:04 web.1  | [14] - Worker 0 (pid: 25) booted, phase: 0
04:02:04 web.1  | [14] - Worker 1 (pid: 27) booted, phase: 0
04:02:04 bot.1  |  ~ (0.000201) SET backslash_quote = off
04:02:04 bot.1  |  ~ (0.000144) SET standard_conforming_strings = on
```

**Comment by seanauriti** [comment]
Is there a way for us to be exempt from logging?

**Comment by placer14** [comment]
@seanauriti On an individual basis? You can only opt-out of participation in the room. If you see `nombot` in the room, assume you're being recording. But that's true of all of slack anyway and considered a moot point.
